name: Create release

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PACKAGE_JSON: "./package.json"
  PACKAGE_PATH: "."


jobs:        
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
        
      - name: Get package properties
        id: package_data
        uses: zoexx/github-action-json-file-properties@1.0.4
        with:
          file_path: "${{ env.PACKAGE_JSON }}"

      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.3.0

      - name: Parse git tag version
        id: tag_version
        uses: madhead/semver-utils@v3.1.0
        with:
          lenient: false
          version: ${{ steps.previous_tag.outputs.tag }}
          compare-to: ${{ steps.package_data.outputs.version }}
        
        
      - name: Track Package Meta Files
        run: |
          find "." -name \*.meta >> metaList
      
      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ steps.package_data.outputs.name }}-${{ steps.tag_version.outputs.inc-prerelease }}.unitypackage
          include-files: metaList
      - name: Create Package Zip
        working-directory: "${{ env.PACKAGE_PATH }}"
        run: zip -r "${{ steps.package_data.outputs.name }}-${{ steps.tag_version.outputs.inc-prerelease }}.zip" .

      - name: Create Tag
        id: create_tag
        uses: rickstaa/action-create-tag@88dbf7ff6fe2405f8e8f6c6fdfd78829bc631f83
        with:
          tag: ${{ steps.tag_version.outputs.inc-prerelease }}
      
      - name: Make Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            ${{ steps.package_data.outputs.name }}-${{ steps.tag_version.outputs.inc-prerelease }}.unitypackage
            ${{ steps.package_data.outputs.name }}-${{ steps.tag_version.outputs.inc-prerelease }}.zip
            ${{ env.PACKAGE_JSON }}
          tag_name: ${{ steps.tag_version.outputs.inc-prerelease }}
          prerelease: true
